# Generated by Django 2.2.12 on 2021-05-30 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('c_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['c_time'],
            },
        ),
        migrations.CreateModel(
            name='customization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('c_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['c_time'],
            },
        ),
        migrations.CreateModel(
            name='sneaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=40)),
                ('img', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='sold',
            fields=[
                ('soldid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('sneakerid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.sneaker')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='buyer', to='shop.buyer', to_field='username')),
                ('custom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.customization')),
                ('inventoryid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.sold')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='seller', to='shop.seller', to_field='username')),
            ],
            options={
                'ordering': ['c_time'],
            },
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.seller', to_field='username')),
                ('sneakerid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.sneaker')),
            ],
        ),
    ]
